version: '3.3'
services:
  web-docker:
    container_name: generator-golang-web
    build: .
    ports:
      - 3001:8082
    volumes:
      - ./web-generator:/app/web-generator
    command: ./web-generator